export {default as Landing } from './Landing'
export {default as HomeLayout } from './HomeLayout'
export {default as Contact} from './Contact'
export {default as About } from './About'
export {default as MoreDetails} from './MoreDetails'
export {default as Pricing } from './PricingDetails'
